#!/usr/bin/env node
import { createHash, createHmac, randomUUID } from 'node:crypto'
import { mkdir, readFile, unlink, writeFile } from 'node:fs/promises'
import { dirname, isAbsolute, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { homedir, tmpdir } from 'node:os'

const here = dirname(fileURLToPath(import.meta.url)), repo = resolve(here, '..')
const names = [
  '服务健康检查','匿名首页可访问','公开户型库含开发种子','管理端账号登录','管理端生成一次性授权码',
  '微信 Stub 登录签发受限会话','受限会话授权快照为 NONE','受保护端点拦截受限会话','授权码兑换并激活',
  '个人资料升级并锁定账号标识','充值方案可购买','充值订单进入待支付','主动对账驱动 Stub 支付','充值到账且点数可见',
  '创建自主设计项目','创建平面任务并扣点','Runtime HMAC 领取平面任务','Runtime 输入快照携带设计需求','Runtime 回写平面隔离区 PNG',
  '驱动器完成平面结算','平面候选按任务晋升','选定平面并开放立面生成','创建立面任务','Runtime HMAC 领取立面任务',
  'Runtime 回写立面隔离区 PNG','驱动器完成立面结算','立面候选晋升并选定','最终结果版本可回读',
  '旧预算冻结规则与输入快照','管理端创建并启用预算地区','管理端启用标准预算项与选项','管理端发布十三项标准价格',
  '管理端新增自定义预算模板并发布区域价格','小程序预算目录只公开可选项且隐藏单价','小程序导入版本绑定的预算参数',
  '小程序生成黄金分项预算并验证重复提交','幂等键异体请求被拒绝且预算未重复','小程序保存预算并在历史中回读',
  '用户覆盖价生效且只影响本人新测算','恢复默认后回基准价且管理端可查历史','覆盖价可补基准缺价并联动目录可用性',
  '管理端读取预算并新增排水沟修订','旧预算修订保持冻结且后台新修订不外泄','管理端创建正式报价草稿且小程序不可见',
  '无预算权限管理员被拒绝','管理端发布报价并验证重复提交','小程序查看脱敏的正式报价',
  '管理端创建并发布调价后第二版报价','旧报价金额冻结且新报价成为当前版',
  '发布前校核通过','用户提交投稿','管理端审核队列可见','审核通过并生成站内信',
  '独立发布且户型库可见','用户统计与 AI 运维读模型可见','人工调点执行双人控制',
  '导出、一次性票据与审计可追溯','解绑后会话实时降级','降级会话访问覆盖价接口被拒'
]
const total = names.length
if (process.argv[2] === '--list') { names.forEach((n,i)=>console.log(`${String(i+1).padStart(2,'0')}. ${n}`)); process.exit(0) }

const id = (process.env.ZS_E2E_RUN_ID || `${Date.now()}-${randomUUID().slice(0,8)}`).replace(/[^\w.-]/g,'-')
const origin = new URL(process.env.ZS_E2E_BASE_URL || 'http://127.0.0.1:48080')
const assetRoot = resolve(process.env.ZS_E2E_ASSET_ROOT || resolve(tmpdir(),'zhongshu-assets'))
const reportDir = resolve(process.env.ZS_E2E_REPORT_DIR || resolve(repo,'artifacts','e2e'))
const timeout = Number(process.env.ZS_E2E_POLL_TIMEOUT_MS || 120000)
const tenant = process.env.ZS_E2E_ADMIN_TENANT_ID || '1'
const secret = process.env.ZS_E2E_INTERNAL_SECRET || 'zsdev-internal-secret-0123456789abcdef'
const checker = process.env.ZS_E2E_CHECKER_TOKEN || 'test100'
const deniedAdmin = process.env.ZS_E2E_DENIED_ADMIN_TOKEN || 'test107'
const runHash = createHash('sha256').update(id).digest('hex').slice(0,12).toUpperCase()
const budgetRegion = `E2E_${runHash}`
const commandKey = purpose => `e2e-${createHash('sha256').update(`${id}:${purpose}`).digest('hex').slice(0,32)}`
const goldenPrices = new Map([
  ['208001',52000],['208006',98000],['208009',52000],['208012',12000],['208015',1800000],
  ['208020',49000],['208023',12000],['208026',12000],['208029',12000],['208030',6000],
  ['208032',8500],['208034',500000],['208035',500000]
])
const S = { results:[], files:[] }
const ok = (v,m)=>{ if(!v) throw new Error(m) }

function safety(){
  ok(['127.0.0.1','localhost','::1','[::1]'].includes(origin.hostname) || process.env.ZS_E2E_ALLOW_REMOTE==='true',
    `拒绝向远程地址 ${origin.origin} 写入；隔离环境需显式设置 ZS_E2E_ALLOW_REMOTE=true`)
  ok(isAbsolute(assetRoot) && assetRoot!==resolve('/') && assetRoot!==resolve(homedir()) && assetRoot!==repo,
    '资产根目录必须是安全的绝对目录，且不能是文件系统、用户或仓库根目录')
}
function url(a,p){ return new URL(`${a==='app'?'/app-api':a==='admin'?'/admin-api':''}${p}`,origin) }
async function raw(a,p,o={}){
  const h=new Headers(o.headers||{}); if(o.token) h.set('Authorization',`Bearer ${o.token}`); h.set('tenant-id',tenant)
  let body; if(o.body!==undefined){body=typeof o.body==='string'?o.body:JSON.stringify(o.body);h.set('Content-Type','application/json')}
  const r=await fetch(url(a,p),{method:o.method||'GET',headers:h,body,signal:AbortSignal.timeout(20000)})
  const bytes=Buffer.from(await r.arrayBuffer()); let json; try{json=JSON.parse(bytes.toString('utf8'))}catch{}
  return {r,bytes,json}
}
async function api(a,p,o={}){const x=await raw(a,p,o);ok(x.r.ok,`${o.method||'GET'} ${p} HTTP ${x.r.status}`);if(x.json&&typeof x.json.code==='number'){ok(x.json.code===0,`${p}: ${x.json.msg||x.json.code}`);return x.json.data}return x.json??x.bytes}
const app=(p,o={})=>api('app',p,{...o,token:o.token||S.appToken})
const admin=(p,o={})=>api('admin',p,{...o,token:o.token||S.adminToken})
async function internal(p,b){const text=JSON.stringify(b),ts=String(Math.floor(Date.now()/1000));const hash=createHash('sha256').update(text).digest('hex');const sig=createHmac('sha256',secret).update(`${ts}\nPOST\n${p}\n${hash}`).digest('hex');return api('internal',p,{method:'POST',body:text,headers:{'X-ZS-Timestamp':ts,'X-ZS-Signature':sig}})}
async function poll(label,fn,pred){const end=Date.now()+timeout;let value;while(Date.now()<end){value=await fn();if(pred(value))return value;await new Promise(r=>setTimeout(r,2000))}throw new Error(`${label} 超时，末态=${JSON.stringify(value)}`)}
async function step(fn){const i=S.results.length,n=names[i],at=Date.now();process.stdout.write(`[${String(i+1).padStart(2,'0')}/${total}] ${n} ... `);try{const detail=await fn();S.results.push({index:i+1,name:n,status:'PASS',durationMs:Date.now()-at,detail});console.log('PASS')}catch(e){S.results.push({index:i+1,name:n,status:'FAIL',durationMs:Date.now()-at,error:e.message});console.log('FAIL');throw e}}
async function claim(jobId,phase){const list=await internal('/internal-api/design/v1/ai-jobs/claims',{workerId:`e2e-${id}-${phase}`,maxJobs:8,phase});const c=list.find(x=>String(x.jobId)===String(jobId));ok(c&&c.phase===phase,`未领取到 ${phase} 任务 ${jobId}`);return c}
async function result(c,phase){const png=Buffer.from((await readFile(resolve(here,'fixtures/tiny-png.base64'),'utf8')).trim(),'base64');ok(png.subarray(0,8).toString('hex')==='89504e470d0a1a0a','PNG fixture 无效');const key=`${c.payload.outputPrefix}/e2e-${id}-${phase}.png`,file=resolve(assetRoot,...key.split('/'));const rel=relative(assetRoot,file);ok(rel&&!rel.startsWith('..')&&!isAbsolute(rel),'Runtime objectKey 逃逸资产根目录');await mkdir(dirname(file),{recursive:true});await writeFile(file,png);S.files.push(file);const base={attemptNo:c.attemptNo,fencingToken:c.fencingToken};ok(await internal(`/internal-api/design/v1/ai-jobs/${c.jobId}/progress-events`,{...base,progress:80,stage:`${phase}_RENDERING`})===true,'进度回写失败');const out=await internal(`/internal-api/design/v1/ai-jobs/${c.jobId}/result-events`,{...base,providerCode:'stub',sourceEventId:`e2e-${id}-${phase}`,candidateSlotNo:1,objectKey:key,sha256:createHash('sha256').update(png).digest('hex'),mimeType:'image/png',sizeBytes:png.length});ok(out==='QUARANTINED','结果未进入隔离区');return out}
async function report(status,started,error){await mkdir(reportDir,{recursive:true});const data={schemaVersion:2,suite:'T02-05-plus-T10-17-plus-T14',provenance:'在仓库重建的 T02-05 基线之上追加 T10-17 真实预算三端链路与 T14 账号覆盖价链路',runId:id,status,startedAt:new Date(started).toISOString(),finishedAt:new Date().toISOString(),passed:S.results.filter(x=>x.status==='PASS').length,total,error:error?.message||null,checkpoints:S.results};const rows=names.map((n,i)=>`| ${i+1} | ${n} | ${S.results[i]?.status||'NOT_RUN'} |`);await writeFile(resolve(reportDir,'latest.json'),JSON.stringify(data,null,2)+'\n');await writeFile(resolve(reportDir,'latest.md'),['# T02-05 + T10-17 + T14 E2E 执行报告','',`- 运行：\`${id}\``,`- 结果：**${status}（${data.passed}/${total}）**`,'- 来源：仓库可重复执行的真实 HTTP / PostgreSQL 三端链路；外部供应商仍使用本地 Stub。','', '| # | 检查点 | 状态 |','|---:|---|---|',...rows,''].join('\n'))}

async function suite(){
  await step(async()=>{const x=await raw('app','/design/v1/home');ok(x.r.ok&&x.json?.code===0&&x.json?.data,'服务未就绪');return 'UP'})
  await step(async()=>{const x=await api('app','/design/v1/home');ok(x&&typeof x==='object','首页无数据');return Object.keys(x).length})
  await step(async()=>{const x=await api('app','/design/v1/cases?limit=20');ok(x.list?.length>0,'无种子案例');return x.list.length})
  await step(async()=>{const x=await api('admin','/system/auth/login',{method:'POST',body:{username:process.env.ZS_E2E_ADMIN_USERNAME||'admin',password:process.env.ZS_E2E_ADMIN_PASSWORD||'admin123',captchaVerification:''}});ok(x.accessToken,'无 admin token');S.adminToken=x.accessToken;const a=await admin('/design/v1/accounts?pageNo=1&pageSize=100');S.oldAccounts=new Set((a.list||[]).map(v=>String(v.id)));return 'authenticated'})
  await step(async()=>{const x=await admin('/design/v1/access-code-batches',{method:'POST',body:{quantity:1,deliveryMode:'INLINE',validityDays:7,purposeNote:`T02-05 ${id}`}});ok(x.oneTimeCodes?.length===1,'未返回一次性明文');S.code=x.oneTimeCodes[0];return x.id})
  await step(async()=>{const x=await api('app','/design/v1/auth/wechat-login',{method:'POST',body:{code:`e2e-${id}`}});ok(x.restricted===true&&x.accessToken,'不是受限会话');S.appToken=x.accessToken;S.refreshToken=x.refreshToken;return x.restricted})
  await step(async()=>{const x=await app('/design/v1/access-grant');ok(x.status==='NONE','授权态非 NONE');return x.status})
  await step(async()=>{const x=await raw('app','/design/v1/point-account',{token:S.appToken});ok(!(x.r.ok&&x.json?.code===0),'受限会话越权');ok(x.json?.code===1070001001,'未激活机器码错误');return x.json?.code||x.r.status})
  await step(async()=>{const x=await app('/design/v1/access-code-redemptions',{method:'POST',body:{accessCode:S.code}});ok(x.status==='ACTIVE','兑换未激活');return x.status})
  await step(async()=>{const p=await app('/design/v1/profile');ok(p.accessGrantStatus==='ACTIVE','profile 未激活');const a=await admin('/design/v1/accounts?pageNo=1&pageSize=100'),fresh=(a.list||[]).filter(v=>!S.oldAccounts.has(String(v.id)));ok(fresh.length===1,'无法唯一识别新账号');S.accountId=String(fresh[0].id);const detail=await admin(`/design/v1/accounts/${S.accountId}`);ok(Number(detail.availablePoints)===0&&!detail.recentLedger.length,'新账号无流水详情异常');return S.accountId})
  await step(async()=>{const x=await app('/design/v1/recharge-plans');ok(x.length,'无充值方案');S.plan=x.find(v=>v.recommended)||x[0];return S.plan.planId})
  await step(async()=>{const x=await app(`/design/v1/recharge-orders?planId=${S.plan.planId}`,{method:'POST',body:null,headers:{'Idempotency-Key':`e2e-${id}-pay`}});ok(x.paymentState==='PENDING','订单非 PENDING');S.order=x;return x.orderId})
  await step(async()=>{const x=await admin(`/design/v1/recharge-orders/${S.order.orderId}/reconciliation`,{method:'POST'});ok(['RECOVERED','ALREADY_RECONCILED'].includes(x),'对账未收口');return x})
  await step(async()=>{const x=await poll('充值到账',()=>app(`/design/v1/recharge-orders/${S.order.orderId}`),v=>v.fulfillmentState==='CREDITED');const p=await app('/design/v1/point-account');ok(p.availablePoints>=x.basePoints+x.bonusPoints,'点数未到账');const history=await app('/design/v1/recharge-orders?pageNo=1&pageSize=20'),saved=history.list?.find(v=>v.orderId===S.order.orderId);ok(saved?.fulfillmentState==='CREDITED'&&saved.amountCents===x.amountCents&&history.total>=1,'充值记录未包含真实到账订单');return p.availablePoints})
  await step(async()=>{const x=await app('/design/v1/design-projects',{method:'POST',body:{sourceType:'SELF_UPLOAD',requirementInputs:{floor:'两层',floorCount:2,family:'5室3厅2卫',rooms:{bedroom:5,living:3,bath:2},faceWidthM:12.6,depthM:13.8,note:`e2e-${id}`,budgetInputs:{regionCode:budgetRegion,footprintArea:'120',floorCount:2,roofArea:'112',quantities:{DOOR_HOUSEHOLDS:'1',CULTURE_STONE_LENGTH:'44',LIGHTING_WASHER_LENGTH:'20',LIGHTING_STRIP_LENGTH:'30',WATERPROOF_AREA:'20'}}}}});ok(x.projectId&&x.stage==='FLAT','项目创建失败');S.projectId=x.projectId;return x.projectId})
  await step(async()=>{const quote=await app('/design/v1/generation-price-quotes?stage=FLAT&count=1');ok(quote.ruleId&&quote.validUntil,'未取得版本化报价');const x=await app(`/design/v1/design-projects/${S.projectId}/flat-jobs`,{method:'POST',body:{count:1,priceConfirmation:{ruleId:quote.ruleId,ruleVersion:quote.ruleVersion,usageConfirmation:{product:quote.usageProduct,ruleId:quote.usageRuleId,ruleVersion:quote.usageRuleVersion}}},headers:{'Idempotency-Key':`e2e-${id}-flat`}});ok(x.jobId,'无平面 jobId');S.flat=String(x.jobId);const restored=await app(`/design/v1/design-projects/${S.projectId}`);ok(restored.jobId===S.flat&&restored.resumeAction==='POLL_JOB','仅项目 ID 不能恢复任务');return S.flat})
  await step(async()=>{S.flatClaim=await claim(S.flat,'FLAT');return S.flatClaim.fencingToken})
  await step(async()=>{const x=await internal(`/internal-api/design/v1/ai-jobs/${S.flat}/inputs`,{attemptNo:S.flatClaim.attemptNo,fencingToken:S.flatClaim.fencingToken}),r=x.requirements||{};ok(r.floor==='两层'&&r.floorCount===2&&r.family==='5室3厅2卫'&&r.faceWidthM==='12.6'&&r.depthM==='13.8'&&r.note===`e2e-${id}`,'平面任务输入缺设计需求键');ok(r.rooms&&r.rooms.bedroom===5&&r.rooms.living===3&&r.rooms.bath===2,'rooms 结构化值缺失');ok(r.budgetInputs&&r.budgetInputs.regionCode===budgetRegion,'budgetInputs 未随快照携带');return Object.keys(r).length})
  await step(async()=>result(S.flatClaim,'FLAT'))
  await step(async()=>{const x=await poll('平面结算',()=>app(`/design/v1/ai-jobs/${S.flat}`),v=>['SUCCEEDED','PARTIALLY_SUCCEEDED'].includes(v.status));ok(x.acceptedCount===1,'平面有效数非 1');return x.status})
  await step(async()=>{const x=await poll('平面晋升',()=>app(`/design/v1/design-projects/${S.projectId}?jobId=${S.flat}`),v=>v.candidates?.length===1);ok(x.candidates.every(v=>String(v.jobId)===S.flat),'候选混阶段');S.flatCandidate=String(x.candidates[0].candidateId);return S.flatCandidate})
  await step(async()=>{const x=await app(`/design/v1/design-projects/${S.projectId}/flat-selections`,{method:'POST',body:{jobId:S.flat,candidateId:S.flatCandidate}});ok(String(x.selectedFlatCandidateId)===S.flatCandidate&&x.allowedActions?.includes('CREATE_ELEVATION_JOB'),'平面选定失败');return x.allowedActions})
  await step(async()=>{const quote=await app('/design/v1/generation-price-quotes?stage=ELEVATION&count=1');const x=await app(`/design/v1/design-projects/${S.projectId}/elevation-jobs`,{method:'POST',body:{count:1,priceConfirmation:{ruleId:quote.ruleId,ruleVersion:quote.ruleVersion,usageConfirmation:{product:quote.usageProduct,ruleId:quote.usageRuleId,ruleVersion:quote.usageRuleVersion}},styleCode:'MODERN',roofType:'GABLE',material:'STONE',color:'WARM_WHITE'},headers:{'Idempotency-Key':`e2e-${id}-elev`}});ok(x.jobId,'无立面 jobId');S.elev=String(x.jobId);return S.elev})
  await step(async()=>{S.elevClaim=await claim(S.elev,'ELEVATION');return S.elevClaim.fencingToken})
  await step(async()=>result(S.elevClaim,'ELEVATION'))
  await step(async()=>{const x=await poll('立面结算',()=>app(`/design/v1/ai-jobs/${S.elev}`),v=>['SUCCEEDED','PARTIALLY_SUCCEEDED'].includes(v.status));ok(x.acceptedCount===1,'立面有效数非 1');return x.status})
  await step(async()=>{const x=await poll('立面晋升',()=>app(`/design/v1/design-projects/${S.projectId}?jobId=${S.elev}`),v=>v.candidates?.some(c=>String(c.jobId)===S.elev)),candidate=x.candidates.find(c=>String(c.jobId)===S.elev);S.elevCandidate=String(candidate.candidateId);const y=await app(`/design/v1/design-projects/${S.projectId}/elevation-selections`,{method:'POST',body:{jobId:S.elev,candidateId:S.elevCandidate}});ok(y.resultVersionId,'无结果版本');S.version=String(y.resultVersionId);return S.version})
  await step(async()=>{const x=await app(`/design/v1/design-projects/${S.projectId}/result-versions`),version=x.list?.find(v=>v.versionId===S.version);ok(version?.selectedFlatAssetId&&version.selectedElevationAssetId,'版本冻结图片不可回读');const projects=await app('/design/v1/design-projects?limit=20');ok(projects.list?.some(v=>v.projectId===S.projectId),'我的方案缺少新项目');for(const assetId of [version.selectedFlatAssetId,version.selectedElevationAssetId]){const ticket=await app(`/design/v1/assets/${assetId}/download-tickets`,{method:'POST'});ok(ticket.ticketId,'方案图片下载授权失败');const resolved=await app(`/design/v1/assets/${assetId}/downloads`,{method:'POST',body:{ticket:ticket.ticketId}});ok(resolved.downloadUrl,'方案图片链接恢复失败')}return x.list.length})
  await step(async()=>{const price=await app('/design/v1/budget-point-quotes'),x=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates`,{method:'POST',headers:{'Idempotency-Key':commandKey('legacy-create')},body:{regionCode:'VAR1',structureType:'BRICK',materialGrade:'A',buildingArea:168,resultVersionId:S.version,usageConfirmation:{product:price.product,ruleId:price.ruleId,ruleVersion:price.ruleVersion}}});ok(x.ruleVersion&&x.inputSnapshot?.regionCode==='VAR1'&&x.totalMinCents<x.totalMaxCents,'旧预算快照无效');S.legacyBudget={estimateId:x.estimateId,ruleVersion:x.ruleVersion,totalMinCents:x.totalMinCents,totalMaxCents:x.totalMaxCents};return S.legacyBudget})
  await step(async()=>{const body={code:budgetRegion,name:`E2E 预算地区 ${runHash}`,enabled:true},key=commandKey('region-create');const x=await admin('/design/v1/budget/regions',{method:'POST',body,headers:{'Idempotency-Key':key}}),replay=await admin('/design/v1/budget/regions',{method:'POST',body,headers:{'Idempotency-Key':key}});ok(x.code===budgetRegion&&x.enabled&&replay.regionId===x.regionId,'地区创建或幂等回放失败');S.region=x;return {regionId:x.regionId,code:x.code}})
  await step(async()=>{const items=await admin('/design/v1/budget/items?pageNo=1&pageSize=100'),standardItems=(items.list||[]).filter(x=>x.source==='STANDARD');ok(standardItems.length===10,'标准预算项身份不完整');let changedItems=0;for(const item of standardItems){if(item.enabled&&item.publicSelectable)continue;await admin(`/design/v1/budget/items/${item.itemId}`,{method:'PATCH',body:{name:item.name,enabled:true,publicSelectable:true,sortOrder:item.sortOrder,expectedVersion:item.version},headers:{'Idempotency-Key':commandKey(`item-enable-${item.itemId}`)}});changedItems++}const options=await admin('/design/v1/budget/options?pageNo=1&pageSize=100'),index=new Map((options.list||[]).map(x=>[x.optionId,x]));let changedOptions=0;const standardIds=new Set(standardItems.map(x=>x.itemId));const allStandardOptions=[...index.values()].filter(x=>standardIds.has(x.itemId));ok(allStandardOptions.length===35,'表格标准选项必须完整包含35项');for(const option of allStandardOptions){const optionId=option.optionId;ok(option,`标准选项缺失 ${optionId}`);if(option.enabled)continue;await admin(`/design/v1/budget/options/${optionId}`,{method:'PATCH',body:{label:option.label,selectionGroup:option.selectionGroup,unit:option.unit,quantitySource:option.quantitySource,quantityKey:option.quantityKey,sourceReference:option.sourceReference,enabled:true,sortOrder:option.sortOrder,expectedVersion:option.version},headers:{'Idempotency-Key':commandKey(`option-enable-${optionId}`)}});changedOptions++}return {items:standardItems.length,options:allStandardOptions.length,changedItems,changedOptions}})
  await step(async()=>{S.standardPriceIds=[];for(const [optionId,unitPriceCents] of goldenPrices){const draft=await admin('/design/v1/budget/prices',{method:'POST',body:{regionCode:budgetRegion,optionId,unitPriceCents,effectiveAt:'2020-01-01T00:00:00Z'},headers:{'Idempotency-Key':commandKey(`price-create-${optionId}`)}}),published=await admin(`/design/v1/budget/prices/${draft.priceId}/publish`,{method:'POST',body:{expectedVersion:draft.version,reason:`T10-17 E2E ${id}`},headers:{'Idempotency-Key':commandKey(`price-publish-${optionId}`)}});ok(published.status==='PUBLISHED'&&published.unitPriceCents===unitPriceCents,`标准价格发布失败 ${optionId}`);S.standardPriceIds.push(published.priceId)}return S.standardPriceIds.length})
  await step(async()=>{const item=await admin('/design/v1/budget/items',{method:'POST',body:{code:`E2E_DRAIN_${runHash}`,name:'排水沟通用模板',category:'EXTERIOR',enabled:true,sortOrder:110},headers:{'Idempotency-Key':commandKey('custom-item-create')}}),option=await admin('/design/v1/budget/options',{method:'POST',body:{itemId:item.itemId,code:'DEFAULT',label:'排水沟施工',selectionGroup:'DEFAULT',unit:'METER',quantitySource:'PROJECT_QUANTITY',quantityKey:'CULTURE_STONE_LENGTH',sourceReference:`T10-17 ${id}`,enabled:true,sortOrder:10},headers:{'Idempotency-Key':commandKey('custom-option-create')}}),draft=await admin('/design/v1/budget/prices',{method:'POST',body:{regionCode:budgetRegion,optionId:option.optionId,unitPriceCents:18000,effectiveAt:'2020-01-01T00:00:00Z'},headers:{'Idempotency-Key':commandKey('custom-price-create')}}),price=await admin(`/design/v1/budget/prices/${draft.priceId}/publish`,{method:'POST',body:{expectedVersion:draft.version,reason:`T10-17 E2E ${id}`},headers:{'Idempotency-Key':commandKey('custom-price-publish')}}),visible=await admin(`/design/v1/budget/items/${item.itemId}`,{method:'PATCH',body:{name:item.name,enabled:true,publicSelectable:true,sortOrder:item.sortOrder,expectedVersion:item.version},headers:{'Idempotency-Key':commandKey('custom-item-open')}});ok(item.source==='CUSTOM_TEMPLATE'&&!item.publicSelectable&&price.status==='PUBLISHED'&&visible.publicSelectable,'自定义预算模板发布失败');S.custom={item,option,price};return {itemId:item.itemId,optionId:option.optionId,priceId:price.priceId}})
  await step(async()=>{const regions=await app('/design/v1/budget/regions'),catalog=await app(`/design/v1/budget/options?regionCode=${encodeURIComponent(budgetRegion)}`),json=JSON.stringify(catalog),options=(catalog.items||[]).flatMap(x=>x.options||[]),available=new Set(options.filter(x=>x.availability==='AVAILABLE').map(x=>x.optionId));const standardVisible=(catalog.items||[]).filter(x=>x.source==='STANDARD').flatMap(x=>x.options||[]);ok(standardVisible.length===35,'小程序必须展示35个标准选项，缺价不能被隐藏');ok((catalog.items||[]).find(x=>x.code==='FOUNDATION')?.options?.length===4,'地基基础必须有4个选项');ok(regions.some(x=>x.code===budgetRegion),'小程序地区目录不可见');for(const optionId of goldenPrices.keys())ok(available.has(optionId),`小程序标准选项不可用 ${optionId}`);ok(available.has(S.custom.option.optionId),'小程序自定义选项不可用');for(const forbidden of ['unitPrice','quantity','sourceReference','freeReason','effectiveAt','publishedBy'])ok(!json.includes(forbidden),`公开目录泄露 ${forbidden}`);return {items:catalog.items.length,available:available.size}})
  await step(async()=>{const x=await app(`/design/v1/design-projects/${S.projectId}/budget-inputs?resultVersionId=${S.version}`);ok(x.importedValues?.regionCode===budgetRegion&&x.importedValues?.footprintArea==='120'&&x.importedValues?.buildingArea==='240'&&x.importedValues?.roofArea==='112'&&x.importedValues?.floorCount===2,'预算参数导入错误');ok(x.missingFields?.length===0&&x.requirementSnapshotIds?.length>0,'预算参数来源不完整');S.requirementSnapshotIds=x.requirementSnapshotIds;return {values:x.importedValues,sources:x.sources,requirementSnapshotIds:x.requirementSnapshotIds}})
  await step(async()=>{const price=await app('/design/v1/budget-point-quotes'),body={resultVersionId:S.version,inputOverrides:{},optionIds:[...goldenPrices.keys()],requirementSnapshotIds:S.requirementSnapshotIds,usageConfirmation:{product:price.product,ruleId:price.ruleId,ruleVersion:price.ruleVersion}},key=commandKey('itemized-create');const x=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',body,headers:{'Idempotency-Key':key}}),replay=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',body,headers:{'Idempotency-Key':key}});ok(x.model==='ITEMIZED_V1'&&x.completeness==='COMPLETE'&&x.totalCents===48202000&&x.items?.length===10,'黄金分项预算不一致');ok(x.categoryTotals?.BODY===35584000&&x.categoryTotals?.EXTERIOR===12618000,'黄金分类小计不一致');ok(replay.budgetId===x.budgetId&&replay.revisionId===x.revisionId,'创建预算幂等回放失败');S.itemized=x;S.itemizedRequest=body;S.itemizedKey=key;return {budgetId:x.budgetId,revisionId:x.revisionId,totalCents:x.totalCents}})
  await step(async()=>{const changed={...S.itemizedRequest,optionIds:S.itemizedRequest.optionIds.slice(0,-1)},r=await raw('app',`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',token:S.appToken,body:changed,headers:{'Idempotency-Key':S.itemizedKey}});ok(!(r.r.ok&&r.json?.code===0),'幂等键异体请求未拒绝');const history=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates`),same=history.filter(x=>String(x.budgetId||x.estimateId)===String(S.itemized.budgetId));ok(same.length===1,'异体请求生成了重复预算');return {code:r.json?.code||r.r.status,count:same.length}})
  await step(async()=>{const x=await app(`/design/v1/budget-estimates/${S.itemized.budgetId}/save`,{method:'POST',headers:{'Idempotency-Key':commandKey('itemized-save')}}),history=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates?savedOnly=true&limit=20`),saved=(history.list||[]).find(v=>String(v.budgetId)===String(S.itemized.budgetId));ok(x.saved===true&&saved?.saved===true&&saved.totalCents===48202000,'保存预算或历史回读失败');return {budgetId:x.budgetId,totalCents:saved.totalCents}})
  await step(async()=>{const my=region=>`/design/v1/budget/my-prices/208001?regionCode=${encodeURIComponent(region)}`;const bad=await raw('app',my(budgetRegion),{method:'PUT',body:{unitPriceCents:0}});ok(!(bad.r.ok&&bad.json?.code===0),'0元覆盖价未被拒绝');const put=await app(my(budgetRegion),{method:'PUT',body:{unitPriceCents:60000,reason:`T14 E2E ${id}`}});ok(put.myPriceCents===60000&&put.priceSource==='ACCOUNT_OVERRIDE'&&put.baselinePriceCents===52000,'覆盖价写入失败');const mine=await app(`/design/v1/budget/my-prices?regionCode=${encodeURIComponent(budgetRegion)}`),row=(mine.groups||[]).flatMap(g=>g.options||[]).find(o=>o.optionId==='208001');ok(row?.priceSource==='ACCOUNT_OVERRIDE'&&row.myPriceCents===60000,'覆盖清单未标记来源或金额');const published=await admin(`/design/v1/budget/prices?regionCode=${encodeURIComponent(budgetRegion)}&optionId=208001&status=PUBLISHED&pageNo=1&pageSize=20`);ok(published.list?.some(p=>p.unitPriceCents===52000&&p.status==='PUBLISHED'),'基准价目录被用户覆盖改写');const estimate=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',body:S.itemizedRequest,headers:{'Idempotency-Key':commandKey('t14-override-estimate')}});ok(estimate.completeness==='COMPLETE'&&estimate.totalCents===49162000,'覆盖价未应用于新测算');const frozen=await app(`/design/v1/budget-estimates/${S.itemized.budgetId}`);ok(frozen.totalCents===48202000,'已保存预算被覆盖价改写');return {budgetId:estimate.budgetId,totalCents:estimate.totalCents,frozenTotal:frozen.totalCents}})
  await step(async()=>{const my=region=>`/design/v1/budget/my-prices/208001?regionCode=${encodeURIComponent(region)}`;const del=await app(my(budgetRegion),{method:'DELETE'}),replay=await app(my(budgetRegion),{method:'DELETE'});ok(del.priceSource==='DEFAULT'&&del.baselinePriceCents===52000,'恢复默认失败');ok(replay.priceSource==='DEFAULT','重复恢复不幂等');const estimate=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',body:S.itemizedRequest,headers:{'Idempotency-Key':commandKey('t14-reset-estimate')}});ok(estimate.totalCents===48202000,'恢复默认后新测算未回基准价');const auditRows=await admin(`/design/v1/budget/account-prices?accountId=${S.accountId}&pageNo=1&pageSize=20`);ok(auditRows.list?.some(r=>r.optionId==='208001'&&r.status==='REMOVED'),'管理端覆盖历史不可查');return {budgetId:estimate.budgetId,totalCents:estimate.totalCents,historyTotal:auditRows.total}})
  await step(async()=>{const catalog=await app(`/design/v1/budget/options?regionCode=${encodeURIComponent(budgetRegion)}`),raftBefore=catalog.items.find(x=>x.code==='FOUNDATION')?.options.find(o=>o.optionId==='208002');ok(raftBefore?.availability==='MISSING_PRICE','无价选项未标记MISSING_PRICE');const put=await app(`/design/v1/budget/my-prices/208002?regionCode=${encodeURIComponent(budgetRegion)}`,{method:'PUT',body:{unitPriceCents:45000}});ok(put.priceSource==='ACCOUNT_OVERRIDE','缺价补价失败');const after=await app(`/design/v1/budget/options?regionCode=${encodeURIComponent(budgetRegion)}`),raftAfter=after.items.find(x=>x.code==='FOUNDATION')?.options.find(o=>o.optionId==='208002');ok(raftAfter?.availability==='AVAILABLE','覆盖价未联动目录可用性');const swap=[...goldenPrices.keys()].map(k=>k==='208001'?'208002':k),estimate=await app(`/design/v1/design-projects/${S.projectId}/budget-estimates/itemized`,{method:'POST',body:{...S.itemizedRequest,optionIds:swap},headers:{'Idempotency-Key':commandKey('t14-fill-estimate')}});ok(estimate.completeness==='COMPLETE'&&estimate.totalCents===47362000,'缺价补价测算错误');await app(`/design/v1/budget/my-prices/208002?regionCode=${encodeURIComponent(budgetRegion)}`,{method:'DELETE'});return {optionId:'208002',totalCents:estimate.totalCents}})
  await step(async()=>{const before=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}`);ok(before.currentVersion===1&&before.totalCents===48202000,'后台初始预算读取错误');S.initialRevisionId=before.revisionId;const body={expectedVersion:1,reason:`T10-17 现场核定 ${id}`,updates:[],additions:[{kind:'PROJECT_CUSTOM',clientKey:`e2e-drain-${runHash}`,itemCode:'DRAINAGE',publicName:'排水沟施工',category:'EXTERIOR',unit:'METER',quantity:'20',unitPriceCents:18000,internalNote:`T10-17 ${id}`}],removeLineIds:[]},key=commandKey('budget-revise'),x=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/revisions`,{method:'POST',body,headers:{'Idempotency-Key':key}}),replay=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/revisions`,{method:'POST',body,headers:{'Idempotency-Key':key}});ok(x.currentVersion===2&&x.revisionNo===2&&x.totalCents===48562000&&x.categoryTotals?.EXTERIOR===12978000,'后台补项复算错误');ok(replay.revisionId===x.revisionId,'预算修订幂等回放失败');S.revision=x;return {revisionId:x.revisionId,totalCents:x.totalCents}})
  await step(async()=>{const old=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}?revisionId=${S.initialRevisionId}`),history=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/revisions`),publicBudget=await app(`/design/v1/budget-estimates/${S.itemized.budgetId}`),json=JSON.stringify(publicBudget);ok(old.readOnly===true&&old.revisionNo===1&&old.totalCents===48202000,'旧预算修订被改写');ok(history.length===2&&history.some(x=>x.revisionNo===1&&x.totalCents===48202000)&&history.some(x=>x.revisionNo===2&&x.totalCents===48562000),'预算修订历史不完整');ok(publicBudget.revisionId===S.initialRevisionId&&publicBudget.totalCents===48202000&&!json.includes(`T10-17 ${id}`),'后台修订向小程序泄露');return {oldTotal:old.totalCents,newTotal:S.revision.totalCents,publicRevisionId:publicBudget.revisionId}})
  await step(async()=>{const body={revisionId:S.revision.revisionId,expectedVersion:2,adjustmentCents:-562000,reason:`T10-17 首版整单调整 ${id}`},key=commandKey('quote-v1-create'),x=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/quotes`,{method:'POST',body,headers:{'Idempotency-Key':key}}),replay=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/quotes`,{method:'POST',body,headers:{'Idempotency-Key':key}}),publicRows=await app(`/design/v1/design-projects/${S.projectId}/budget-quotes`);ok(x.status==='DRAFT'&&x.calculatedTotalCents===48562000&&x.adjustmentCents===-562000&&x.finalPriceCents===48000000,'首版报价草稿金额错误');ok(replay.quoteId===x.quoteId&&publicRows.length===0,'草稿幂等或公开隔离失败');S.quote1=x;return {quoteId:x.quoteId,status:x.status,finalPriceCents:x.finalPriceCents}})
  await step(async()=>{const r=await raw('admin','/design/v1/budget/regions?pageNo=1&pageSize=1',{token:deniedAdmin});ok(!(r.r.ok&&r.json?.code===0),'无预算权限账号越权查询目录');ok(r.r.status===403||r.json?.code===403,`无权限响应码异常 ${r.r.status}/${r.json?.code}`);return r.json?.code||r.r.status})
  await step(async()=>{const body={expectedVersion:1,reason:`T10-17 首版复核 ${id}`},key=commandKey('quote-v1-publish'),x=await admin(`/design/v1/budget/quotes/${S.quote1.quoteId}/publish`,{method:'POST',body,headers:{'Idempotency-Key':key}}),replay=await admin(`/design/v1/budget/quotes/${S.quote1.quoteId}/publish`,{method:'POST',body,headers:{'Idempotency-Key':key}}),rows=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/quotes`);ok(x.status==='PUBLISHED'&&x.currentPublic&&replay.quoteId===x.quoteId,'首版报价发布幂等失败');ok(rows.filter(v=>v.quoteId===x.quoteId).length===1,'重复发布产生了重复报价');S.quote1=x;return {quoteId:x.quoteId,status:x.status,currentPublic:x.currentPublic}})
  await step(async()=>{const rows=await app(`/design/v1/design-projects/${S.projectId}/budget-quotes`),x=rows.find(v=>v.quoteId===S.quote1.quoteId),json=JSON.stringify(x);ok(rows.length===1&&x?.current===true&&x.finalPriceCents===48000000&&x.calculatedTotalCents===48562000,'小程序首版正式报价错误');for(const forbidden of ['reason','unitPriceCents','internalNote','sourceReference'])ok(!json.includes(forbidden),`正式报价泄露 ${forbidden}`);/* f1bd4188 数量透明决策后，报价行与明细共用 Line VO 携带 quantity 展示，不再列为禁泄露字段 */return {quoteId:x.quoteId,current:x.current,finalPriceCents:x.finalPriceCents}})
  await step(async()=>{const body={revisionId:S.revision.revisionId,expectedVersion:2,finalPriceCents:48010000,reason:`T10-17 二版调价 ${id}`},draft=await admin(`/design/v1/budget/estimates/${S.itemized.budgetId}/quotes`,{method:'POST',body,headers:{'Idempotency-Key':commandKey('quote-v2-create')}}),x=await admin(`/design/v1/budget/quotes/${draft.quoteId}/publish`,{method:'POST',body:{expectedVersion:1,reason:`T10-17 二版复核 ${id}`},headers:{'Idempotency-Key':commandKey('quote-v2-publish')}});ok(draft.quoteVersion===2&&draft.calculatedTotalCents===48562000&&draft.adjustmentCents===-552000&&draft.finalPriceCents===48010000,'二版调价复算错误');ok(x.status==='PUBLISHED'&&x.currentPublic,'二版报价发布失败');S.quote2=x;return {quoteId:x.quoteId,quoteVersion:x.quoteVersion,adjustmentCents:x.adjustmentCents,finalPriceCents:x.finalPriceCents}})
  await step(async()=>{const rows=await app(`/design/v1/design-projects/${S.projectId}/budget-quotes`),current=rows.find(x=>x.quoteId===S.quote2.quoteId),old=await app(`/design/v1/design-projects/${S.projectId}/budget-quotes/${S.quote1.quoteId}`),adminOld=await admin(`/design/v1/budget/quotes/${S.quote1.quoteId}`);ok(rows.length===2&&current?.current===true&&current.finalPriceCents===48010000,'二版报价未成为当前版');ok(old.current===false&&old.status==='PUBLISHED'&&old.finalPriceCents===48000000&&old.calculatedTotalCents===48562000,'旧报价金额或状态被改写');ok(adminOld.currentPublic===false&&adminOld.finalPriceCents===48000000,'后台旧报价快照不稳定');return {currentQuoteId:current.quoteId,currentFinal:current.finalPriceCents,oldQuoteId:old.quoteId,oldFinal:old.finalPriceCents}})
  const submission=()=>({resultVersionId:S.version,publicDisplayGranted:true,generationReferenceGranted:true,note:`T02-05 ${id}`})
  await step(async()=>{const x=await app(`/design/v1/design-projects/${S.projectId}/publication-validations`,{method:'POST',body:submission()});ok(x.valid===true&&!x.missingFields.length,'发布校核失败');return x.valid})
  await step(async()=>{const x=await app(`/design/v1/design-projects/${S.projectId}/submissions`,{method:'POST',body:submission(),headers:{'Idempotency-Key':`e2e-${id}-submit`}});ok(x.status==='SUBMITTED','投稿失败');S.submission=String(x.submissionId);const history=await app('/design/v1/submissions?limit=20'),detail=await app(`/design/v1/submissions/${S.submission}`);ok(history.list?.some(v=>v.submissionId===S.submission)&&detail.projectId===S.projectId&&detail.resultVersionId===S.version,'投稿记录不能定位原方案');return S.submission})
  await step(async()=>{const x=await admin('/design/v1/submissions?status=SUBMITTED&pageNo=1&pageSize=100');ok(x.list?.some(v=>String(v.submissionId)===S.submission),'审核队列无投稿');return x.total})
  await step(async()=>{const x=await admin(`/design/v1/submissions/${S.submission}/review-decisions`,{method:'POST',body:{decision:'APPROVE',comment:`E2E ${id}`}});ok(x.status==='APPROVED','审核失败');const m=await poll('站内信',()=>app('/design/v1/messages?limit=50'),v=>v.list?.some(z=>z.messageType==='SUBMISSION_REVIEWED'&&String(z.bizId)===S.submission));return m.list.length})
  await step(async()=>{const x=await admin(`/design/v1/submissions/${S.submission}/publication-commands`,{method:'POST'});ok(x.publishedCaseId,'发布失败');S.caseId=String(x.publishedCaseId);const c=await poll('案例上架',()=>api('app','/design/v1/cases?sourceType=AI&limit=50'),v=>v.list?.some(z=>String(z.caseId)===S.caseId));const submitted=await app(`/design/v1/submissions/${S.submission}`);ok(submitted.publicationStatus==='PUBLISHED'&&submitted.reviewComment===`E2E ${id}`,'投稿记录未同步审核意见及发布状态');ok(await app(`/design/v1/cases/${S.caseId}/favorite`,{method:'PUT'})===true,'收藏失败');const saved=await app('/design/v1/favorites?limit=20');ok(saved.list?.some(v=>v.caseId===S.caseId),'收藏记录未保存');ok(await app(`/design/v1/cases/${S.caseId}/favorite`,{method:'DELETE'})===true,'取消收藏失败');const removed=await app('/design/v1/favorites?limit=20');ok(!removed.list?.some(v=>v.caseId===S.caseId),'取消后仍在收藏记录');return c.list.length})
  await step(async()=>{const a=await admin(`/design/v1/accounts/${S.accountId}`);S.grant=String(a.grants?.find(v=>v.status==='ACTIVE')?.id||'');ok(S.grant,'用户无有效授权');const d=await admin('/design/v1/dashboard/summary'),j=await admin('/design/v1/ai-jobs?pageNo=1&pageSize=100'),ids=new Set(j.list.map(v=>String(v.jobId)));ok(d.accountsActive>=1&&ids.has(S.flat)&&ids.has(S.elev),'运营读模型缺数据');return j.total})
  await step(async()=>{const x=await admin('/design/v1/manual-point-adjustments',{method:'POST',body:{targetUserId:S.accountId,delta:1,reason:`T02-05 ${id}`}});const self=await raw('admin',`/design/v1/manual-point-adjustments/${x.adjustmentId}/review-decisions`,{method:'POST',token:S.adminToken,body:{approve:true,comment:'self'}});ok(!(self.r.ok&&self.json?.code===0),'同人复核未拒绝');const y=await admin(`/design/v1/manual-point-adjustments/${x.adjustmentId}/review-decisions`,{method:'POST',token:checker,body:{approve:true,comment:'checker'}});ok(y.status==='EXECUTED','双人调点未执行');return y.status})
  await step(async()=>{const x=await admin('/design/v1/export-jobs',{method:'POST',body:{jobType:'POINT_LEDGER',runId:id}});const done=await poll('导出 worker',()=>admin(`/design/v1/export-jobs/${x.exportJobId}`),v=>v.status==='COMPLETED');const t=await admin(`/design/v1/export-jobs/${x.exportJobId}/download-tickets`,{method:'POST'});ok(t.ticket,'无下载票据');const f=await raw('admin',`/design/v1/export-jobs/${x.exportJobId}/content?ticket=${encodeURIComponent(t.ticket)}`,{token:S.adminToken});ok(f.r.ok&&f.bytes.toString('utf8').includes('流水号'),'CSV 下载失败');const audit=await admin('/design/v1/audit-events?pageNo=1&pageSize=100');ok(audit.total>0,'无审计记录');return {exportJobId:done.exportJobId,auditTotal:audit.total}})
  await step(async()=>{ok(await admin(`/design/v1/access-grants/${S.grant}/revocations`,{method:'POST'})===true,'解绑失败');const g=await app('/design/v1/access-grant');ok(g.status==='NONE','会话未降级');const p=await raw('app','/design/v1/point-account',{token:S.appToken});ok(!(p.r.ok&&p.json?.code===0),'降级后仍可访问业务');return g.status})
  await step(async()=>{const list=await raw('app',`/design/v1/budget/my-prices?regionCode=${encodeURIComponent(budgetRegion)}`,{token:S.appToken});ok(list.json?.code===1070001001,'降级会话未拦截覆盖价查询');const put=await raw('app',`/design/v1/budget/my-prices/208001?regionCode=${encodeURIComponent(budgetRegion)}`,{method:'PUT',token:S.appToken,body:{unitPriceCents:60000}});ok(put.json?.code===1070001001,'降级会话未拦截覆盖价写入');const del=await raw('app',`/design/v1/budget/my-prices/208001?regionCode=${encodeURIComponent(budgetRegion)}`,{method:'DELETE',token:S.appToken});ok(del.json?.code===1070001001,'降级会话未拦截恢复默认');return {code:list.json?.code}})
}

safety()
if(process.argv[2]==='--validate'){const p=Buffer.from((await readFile(resolve(here,'fixtures/tiny-png.base64'),'utf8')).trim(),'base64');ok(p.subarray(0,8).toString('hex')==='89504e470d0a1a0a','fixture 无效');console.log(`[e2e] 离线校验通过：${total} 个检查点`);process.exit(0)}
const started=Date.now();let failure
try{await suite();ok(S.results.length===total,'检查点未完整执行')}catch(e){failure=e;console.error(`\n[e2e] ${e.message}`)}finally{for(const f of S.files){try{await unlink(f)}catch(e){if(e.code!=='ENOENT')console.error(`[e2e] 清理失败 ${f}: ${e.message}`)}}await report(failure?'FAIL':'PASS',started,failure)}
if(failure)process.exit(1);console.log(`\n[e2e] ${total}/${total} PASS，报告：${resolve(reportDir,'latest.md')}`)
