### /promotion/bargain-record/create 创建砍价记录
POST {{appApi}}/promotion/bargain-record/create
Authorization: Bearer REPLACE_ME
Content-Type: application/json
tenant-id: {{appTenantId}}

{
  "activityId": 1
}
